name: Generate README.md

on: workflow_dispatch

jobs:
  generate:
    name: Resolve latest artifacts and write README.md
    strategy:
      fail-fast: true
      matrix:
        python-version: ["3.12"]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install requests mdutils
      - name: Generate README.md
        run: python generate_readme.py
      - uses: EndBug/add-and-commit@v9
        with:
          add: "README.md"
          message: "Generated README.md"
          pathspec_error_handling: exitImmediately
